"""
Evaluate <dataset>/vqa.json's multiple-choice questions against a Gemini judge model.

For each vqa.json item, builds:
  - a ground_truth_actions.json text context
  - a transcript text context: only label_annotations.json entries tagged ACTION or GOAL,
    reduced to just {start, end, transcript_text}
  - a video clip
  - the multiple-choice answers, shuffled per item (deterministic seed) and lettered A/B/C/...

Per-stage context scope (mirrors how each question type's context was built when it was
generated by query_gemini_annotations.py):
  - stage1 (all 4 target categories): ground_truth_actions and the ACTION/GOAL transcript are
    both cut off at the source annotation's reference_end (same cutoff stage1 generation
    used); video is that item's original narrow ~30s clip (from gemini_queries.json's
    video_window, floored to VIDEO_FLOOR_SECONDS), sampled at 1fps. Nothing here is shared
    across items, so each stage1 call sends its context/video fresh, uncached.
  - stage2 (PLAN) and stage3 (ASSESSMENT): the transcript is the FULL history, but the
    ground-truth actions are sent as TIMESTAMPS ONLY (descriptions withheld) so the model can't
    answer these timestamp questions by looking the action up in the sheet — it must use the
    video to determine what happens at each candidate time. Video is one shared clip of the
    whole recording (encoded from 0s at STAGE23_FPS, downscaled), with the pre-VIDEO_FLOOR intro
    excluded via VideoMetadata.start_offset rather than by cutting — so the model perceives
    events in ORIGINAL video time, matching the timestamp answers (verified: with start_offset
    the model timestamps events in original coordinates, so no label shifting is needed). This
    shared video clip — identical across every stage2/3 item and, more importantly, across
    every eval setting that keeps the same video encoding — is cached ONCE in a Vertex AI
    CachedContent and referenced by every stage2/3 call. The text context (ground_truth/
    transcript) is deliberately kept OUT of that cache and sent inline on every call instead:
    unlike the video, it changes with nearly every baseline flag combination, and re-bundling it
    into the cache key would force a full cache rebuild (re-encoding + re-uploading the whole
    video) on every such change just to swap out its cheap, small part. With --no-cache the video
    is sent inline too (no Vertex caching at all), for validating the basic flow. Stage2 questions
    describe "the current point" (e.g. "the experimenter is currently increasing the stirring
    speed") without stating it, and since the history above is sent uncut, nothing else pins that
    moment down — so each stage2 item's vqa.json current_point (build_vqa.py's carry-through of
    Gemini's own future_event identification from stage2 generation) is stated as text, always,
    regardless of --no-video.
  - interview (prose "why" answers, same shape as stage1): text context is the SAME full-history
    pipeline stage2/3 use (ground_truth_actions + the ACTION/GOAL-or-raw transcript) — every
    baseline flag (--no-action/--no-goal/--no-ground-truth/--no-timestamps/--raw-transcript, plus
    --no-video/--only-video/--no-text) applies to it exactly as it does for stage2/3. Video is the
    WHOLE reference video, one shared Vertex CachedContent across every interview item — reusing
    the exact cache query_gemini_annotations.py --interview and generate_adversarial_grounded.py
    already built (same key format, so a default-model run hits it instead of re-encoding) —
    since a cached video's own metadata can't be overridden per call, each item's
    [reference_start, reference_end] (read from interview_queries.json) is instead stated as text
    in the prompt whenever video is sent.

The context (video clip + ground-truth actions + transcript) is ALWAYS delivered as separate
Parts — inline for stage1, text always inline for stage2/3, video inline under --no-cache or via
the cache otherwise — never embedded in the prompt string. PROMPT_TEMPLATE is therefore a
placeholder that receives only {question} and {choices_block} (a lettered "A) ...\nB) ..."
block); fill in the actual judge-model prompt there.

Answer choices are shuffled with a per-item deterministic seed (annotation_id + stage) so
reruns are reproducible, and labeled A/B/C/...; the correct letter is recorded in the output
for scoring — it is never revealed to the model.

Output is written incrementally to <dataset>/eval_results.json, keyed by "annotation_id:stage"
so re-running skips items already evaluated.

--no-video runs a no-video baseline instead: no video is sent at all (only the same per-stage
text context), writing to <dataset>/eval_results_no_video.json so it doesn't clobber the
with-video results — for comparing how much accuracy the video itself is contributing.

--no-goal runs a no-goal baseline: the ACTION/GOAL transcript context drops its GOAL-tagged
lines, leaving only ACTION lines, so the model doesn't get the experimenter's stated goals as
text context — for comparing how much accuracy that GOAL context is contributing. Writes to
<dataset>/eval_results_no_goal.json (or eval_results_no_video_no_goal.json if combined with
--no-video) so it doesn't clobber the other variants.

--only-video runs an only-video baseline: the inverse of --no-video — video is sent but NO
textual context at all (no ground_truth_actions, no ACTION/GOAL transcript), so the model must
answer from the video alone. Mutually exclusive with --no-video. Writes to
<dataset>/eval_results_only_video.json.

--no-action drops ACTION-tagged lines from the ACTION/GOAL transcript context, leaving only GOAL
lines (the inverse of --no-goal). Combine with the default (video on) to test "video + GOAL only,
no other transcript". Mutually exclusive with --no-goal (together they'd leave no transcript at
all) and with --only-video (which already drops all text). Adds a _no_action suffix to the output
filename.

--no-text drops ALL textual context regardless of the video setting — a more general form of
--only-video that can combine with --no-video. --no-video + --no-text together is the fully blind
floor: no video, no text, just the question and answer choices (a new PROMPT_TEMPLATE_BLIND is
used for this combo, since neither PROMPT_TEMPLATE_NO_VIDEO nor PROMPT_TEMPLATE_ONLY_VIDEO fits
when both are gone). Mutually exclusive with --only-video/--no-goal/--no-action (all redundant
once all text is dropped). Adds a _no_text suffix to the output filename.

--no-timestamps drops the start/end fields from each transcript entry before it's sent, leaving
only its text — so the model gets what was said but not when, and can't read event timing
directly off the transcript. Ground-truth action timestamps (stage1's descriptions-with-times,
stage2/3's bare candidate timespans) are untouched, since those aren't "the transcript" and
stage2/3 questions require them. Mutually exclusive with --only-video/--no-text (no transcript is
sent in either case, so there'd be nothing to strip timestamps from). Adds a _no_timestamps
suffix to the output filename.

--no-ground-truth drops the ground_truth_actions context entirely (stage1's cutoff descriptions
and stage2/3's timestamps-only list), leaving only the transcript as textual context. Mutually
exclusive with --only-video/--no-text (both already drop this, making it redundant). Adds a
_no_ground_truth suffix to the output filename.

--raw-transcript swaps the transcript source from the ACTION/GOAL-only categorized subset (drawn
from label_annotations.json) to the complete original transcript file that label_annotations.json
itself was generated from (named by its "transcript_file" field, under <dataset>/transcripts/) —
every line, regardless of category, exactly as transcribed. Supports both that file's JSON form
(a list of {id, start, end, text, speaker, ...}) and plain-text form ("[H:MM:SS.mmm] text" per
line, start only, as in session02's transcript). Since the raw transcript has no ACTION/GOAL
categories, this is mutually exclusive with --no-goal/--no-action. Stage1 still truncates it at
the item's reference_end (matching the existing anti-spoiler cutoff); stage2/3 still get the full
history, uncut. Adds a _raw_transcript suffix to the output filename.

--raw-transcript --no-ground-truth (+ --no-timestamps for the no-timestamps variant) is the
"full-context" setting: video + the literal, complete transcript and nothing else. Together with
--only-video (video-only) and --no-video --no-text (blind), it forms the three main evaluation
settings.

Usage:
    python3 vqa_pipeline/evaluate_vqa.py --dataset session01
    python3 vqa_pipeline/evaluate_vqa.py --dataset session01 --stage stage3 --limit 1 --no-cache --max-clip-seconds 120
    python3 vqa_pipeline/evaluate_vqa.py --dataset session01 --no-video
    python3 vqa_pipeline/evaluate_vqa.py --dataset session01 --no-goal
    python3 vqa_pipeline/evaluate_vqa.py --dataset session01 --only-video
    python3 vqa_pipeline/evaluate_vqa.py --dataset session01 --raw-transcript --no-ground-truth --no-timestamps
    python3 vqa_pipeline/evaluate_vqa.py --dataset session01 --only-video --hard-only
"""

import argparse
import json
import os
import random
import re
import string
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import httpx
from tenacity import retry, stop_after_attempt, wait_random_exponential, retry_if_exception

import vertex_cache
from goal_context import load_goal_folder_text
from dataset_config import video_floor_seconds


def _is_retryable(exc: BaseException) -> bool:
    """Retry transient network errors AND Vertex rate-limit / server errors — 429
    RESOURCE_EXHAUSTED especially, since a full run can still burst past the per-minute cap
    (google.genai raises ClientError/ServerError carrying a numeric code). httpx.TransportError
    covers ReadError/ConnectError/*Timeout — the underlying httpx client raises these directly
    (e.g. "Connection reset by peer"), bypassing google.genai's ClientError/ServerError wrapping,
    so they need their own check rather than falling through the status-code path below."""
    if isinstance(exc, (ConnectionError, TimeoutError, httpx.TransportError)):
        return True
    code = getattr(exc, "code", None) or getattr(exc, "status_code", None)
    return code in (408, 429, 500, 502, 503, 504)


def _response_metadata(response) -> dict:
    """Everything worth keeping from a GenerateContentResponse besides the text itself: full
    token accounting (prompt/output/cached/thinking tokens) plus per-call diagnostics. Captured
    for every call so token spend is auditable after the fact instead of discarded."""
    usage = response.usage_metadata
    candidate = response.candidates[0] if response.candidates else None
    return {
        "model_version": response.model_version,
        "response_id": response.response_id,
        "create_time": response.create_time.isoformat() if response.create_time else None,
        "usage": usage.model_dump(mode="json", exclude_none=True) if usage else None,
        "finish_reason": candidate.finish_reason.value if candidate and candidate.finish_reason else None,
        "finish_message": candidate.finish_message if candidate else None,
    }


REPO_ROOT = Path(__file__).resolve().parent.parent
ANNOTATION_VIDEOS_DIR = Path(os.environ.get("COGVQA_DATA_DIR", REPO_ROOT / "data"))
DOTENV_FILE = REPO_ROOT / ".env"

MODEL = "gemini-3.1-pro-preview"
VERTEX_LOCATION = "global"

STAGE1_FPS = 1.0
STAGE23_FPS = 0.5               # 1 frame per 2 seconds
STAGE_VIDEO_SCALE_WIDTH = 480   
STAGE1_CRF = 28
STAGE23_CRF = 32                # the shared whole-video clip must stay under the CachedContent
                                # inline size limit (~10MB); crf 32 @480p/0.5fps lands ~8.5MB.
                                # Vertex Express service accounts can't use the GCS file_uri path
                                # the API suggests for larger caches, so inline size is the ceiling.
STAGE23_CACHE_MAX_BYTES = 9_500_000
# gemini-3.1-flash-lite hit "cached content exceeds the data size limit" on session04's ~88min
# video at a clip that fit fine (same bytes) under the default model's ~9.5MB ceiling — Flash-Lite
# appears to have a smaller CachedContent inline limit than Pro. No documented number, so this is
# a conservative guess; encode_under_size_limit's CRF-bump retry loop compresses further to hit it.
STAGE23_CACHE_MAX_BYTES_BY_MODEL = {
    "gemini-3.1-flash-lite": 4_500_000,
}
STAGE23_CACHE_TTL_SECONDS = 21600  # 6h: 7200 (2h) turned out too short — a full run's per-call
                                    # judge latency (long thinking passes) can push total wall
                                    # time well past 2h, expiring the cache mid-run (observed)

# interview-stage: MUST match query_gemini_annotations.py's INTERVIEW_* constants exactly (same
# cache key format, so a default-model run hits the cache that script and
# generate_adversarial_grounded.py already built instead of re-encoding the whole reference video).
INTERVIEW_FPS = 0.5
INTERVIEW_VIDEO_SCALE_WIDTH = 480
INTERVIEW_CRF = 32
INTERVIEW_CACHE_TTL_SECONDS = 21600

INFERENCE_TEMPERATURE = 0.0     # judging, not generation — deterministic scoring matters more
MIN_SECONDS_BETWEEN_CALLS = 3.0  # proactive throttle: pace calls (~20/min) to mostly avoid 429s
                                 # rather than eat long backoffs after hitting them

PROMPT_TEMPLATE = """
    Answer the following multiple-choice question based on the video and the provided context of the experimenter's comments.

    Question: {question}

    {choices_block}.

    Respond only with the letter of the best answer to the question.
"""

# --no-video variant: no video is actually sent (only the text context, per the normal per-stage
# rules), so the model is told outright it can't see the video and to reason about the likely
# timeline instead, rather than being asked to do something it can't (the base PROMPT_TEMPLATE
# tells it to answer "based on the video").
PROMPT_TEMPLATE_NO_VIDEO = """
    Answer the following multiple-choice question about a chemistry experiment. You will NOT be
    shown the video. Instead, using the provided context of the experimenter's comments, imagine
    how the events of the experiment might plausibly unfold over its roughly {video_duration}
    timeframe, and use that reasoning to judge which answer is most likely correct.

    Question: {question}

    {choices_block}.

    Respond only with the letter of the correct answer.
"""

# --only-video variant: video is sent but NO textual context at all (no ground_truth_actions,
# no ACTION/GOAL transcript) — the inverse of --no-video, isolating how much accuracy the video
# alone contributes without any text scaffolding.
PROMPT_TEMPLATE_ONLY_VIDEO = """
    Answer the following multiple-choice question based ONLY on the video. No textual context
    about the experimenter's comments or the experiment's ground-truth action log is provided —
    rely solely on what you observe in the video.

    Question: {question}

    {choices_block}.

    Respond only with the letter of the best answer to the question.
"""

# --no-video --no-text combo: neither video nor any textual context at all — the fully blind
# floor. Distinct from PROMPT_TEMPLATE_NO_VIDEO (which still expects text context to reason
# from) and PROMPT_TEMPLATE_ONLY_VIDEO (which still expects video); this one has neither.
PROMPT_TEMPLATE_BLIND = """
    Answer the following multiple-choice question about a chemistry experiment to the best of your ability. You will NOT be shown a video, but you can imagine how the events of the experiment might plausibly unfold over its roughly {video_duration}.

    Question: {question}

    {choices_block}.

    Respond only with the letter of the best answer to the question.
"""


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset", required=True, help="Dataset folder name, e.g. session01")
    parser.add_argument("--model", default=MODEL,
                         help=f"Vertex model id to judge with (default: {MODEL}). Output filenames get a "
                              "_model_<slug> suffix for any non-default model, so a cheaper/other model's "
                              "results never overwrite the default model's baseline files.")
    parser.add_argument("--limit", type=int, default=None, help="Only evaluate the first N remaining items (for testing)")
    parser.add_argument("--stage", choices=["stage1", "stage2", "stage3", "interview"], default=None,
                         help="Restrict to one stage before applying --limit")
    parser.add_argument("--hard-only", action="store_true",
                         help="Restrict to items the dataset's own blind run "
                              "(eval_results_no_video_no_text.json — run --no-video --no-text first) "
                              "answered WRONG — the 'hard' subset a setting actually has to earn its "
                              "accuracy on, since blind gets these right by guessing/phrasing alone on "
                              "the rest. An item blind hasn't evaluated yet, or whose response didn't "
                              "parse to a letter, is excluded (not counted as hard OR easy) rather than "
                              "assumed either way — matches the once-manual hard-filtering convention "
                              "(see scoring.blind_wrongness). Writes into the same "
                              "eval_results*.json this setting always uses — no separate dataset "
                              "directory needed; a later run without --hard-only just fills in the "
                              "easy items that were skipped, in the same file.")
    parser.add_argument("--no-cache", action="store_true",
                         help="Send stage2/3 shared context (video + full history text) inline on every "
                              "call instead of via a Vertex CachedContent. Use to validate the basic flow "
                              "before trusting the cache path.")
    parser.add_argument("--max-clip-seconds", type=float, default=None,
                         help="Cap the stage2/3 shared clip length (from VIDEO_FLOOR_SECONDS) for testing, "
                              "so it stays small instead of spanning the whole video.")
    parser.add_argument("--temperature", type=float, default=INFERENCE_TEMPERATURE,
                         help=f"Override INFERENCE_TEMPERATURE (default: {INFERENCE_TEMPERATURE}). A "
                              "non-default value gets its own _tempN suffix so it never overwrites the "
                              "baseline temperature's results.")
    parser.add_argument("--no-video", action="store_true",
                         help="No-video baseline: send no video at all (only the same per-stage text "
                              "context) so results are comparable against the with-video eval. Writes to "
                              "a separate eval_results_no_video.json rather than eval_results.json.")
    parser.add_argument("--no-goal", action="store_true",
                         help="No-goal baseline: drop GOAL-tagged lines from the ACTION/GOAL transcript "
                              "context, leaving only ACTION lines, so results are comparable against the "
                              "full-context eval. Combines with --no-video. Adds a _no_goal suffix to the "
                              "output filename.")
    parser.add_argument("--no-action", action="store_true",
                         help="No-action baseline: drop ACTION-tagged lines from the ACTION/GOAL transcript "
                              "context, leaving only GOAL lines. E.g. combine with the default (video on) to "
                              "get 'video + GOAL only, no other transcript'. Mutually exclusive with --no-goal "
                              "(that would leave nothing) and with --only-video (which already drops all text). "
                              "Adds a _no_action suffix to the output filename.")
    parser.add_argument("--only-video", action="store_true",
                         help="Only-video baseline: send the video but NO textual context at all (no "
                              "ground_truth_actions, no ACTION/GOAL transcript) — the inverse of --no-video. "
                              "Mutually exclusive with --no-video. Writes to a separate "
                              "eval_results_only_video.json.")
    parser.add_argument("--no-text", action="store_true",
                         help="Drop ALL textual context (no ground_truth_actions, no ACTION/GOAL transcript) "
                              "regardless of the video setting — a more general form of --only-video that can "
                              "combine with --no-video. --no-video + --no-text together is the fully blind "
                              "floor: no video, no text, just the question and choices. Mutually exclusive with "
                              "--only-video, --no-goal, and --no-action (all redundant once all text is gone). "
                              "Adds a _no_text suffix to the output filename.")
    parser.add_argument("--no-timestamps", action="store_true",
                         help="Full-context baseline: keep video + the full ACTION/GOAL transcript, but drop "
                              "the start/end fields from each transcript entry (only transcript_text is sent), "
                              "so the model can't read event timing directly off the transcript. Ground-truth "
                              "action timestamps are unaffected. Mutually exclusive with --only-video/--no-text "
                              "(no transcript is sent in either case). Adds a _no_timestamps suffix to the "
                              "output filename.")
    parser.add_argument("--no-ground-truth", action="store_true",
                         help="Drop the ground_truth_actions context entirely (stage1's cutoff descriptions "
                              "and stage2/3's timestamps-only list), leaving only the ACTION/GOAL transcript "
                              "(still subject to --no-goal/--no-action) as textual context. E.g. combine with "
                              "--no-action for 'video + GOAL-transcript-only, no ground truth actions'. "
                              "Mutually exclusive with --only-video/--no-text (both already drop this). Adds a "
                              "_no_ground_truth suffix to the output filename.")
    parser.add_argument("--raw-transcript", action="store_true",
                         help="Use the complete original transcript (every line, any category) from the "
                              "dataset's source transcript file (named by label_annotations.json's "
                              "\"transcript_file\" field, under <dataset>/transcripts/) instead of the "
                              "ACTION/GOAL-only categorized subset. Mutually exclusive with --no-goal/"
                              "--no-action (no category filtering applies to the raw transcript) and with "
                              "--only-video/--no-text (no transcript is sent in either case). Adds a "
                              "_raw_transcript suffix to the output filename.")
    args = parser.parse_args()
    if args.no_video and args.only_video:
        parser.error("--no-video and --only-video are mutually exclusive")
    if args.no_action and args.no_goal:
        parser.error("--no-action and --no-goal are mutually exclusive (together they'd leave no transcript at all)")
    if args.no_action and args.only_video:
        parser.error("--no-action and --only-video are mutually exclusive (--only-video already drops all text)")
    if args.no_text and (args.only_video or args.no_goal or args.no_action):
        parser.error("--no-text is mutually exclusive with --only-video/--no-goal/--no-action "
                      "(all redundant once all text is dropped)")
    if args.no_timestamps and (args.only_video or args.no_text):
        parser.error("--no-timestamps is mutually exclusive with --only-video/--no-text "
                      "(no transcript is sent in either case)")
    if args.no_ground_truth and (args.only_video or args.no_text):
        parser.error("--no-ground-truth is mutually exclusive with --only-video/--no-text "
                      "(both already drop the ground_truth_actions context)")
    if args.raw_transcript and (args.only_video or args.no_text):
        parser.error("--raw-transcript is mutually exclusive with --only-video/--no-text "
                      "(no transcript is sent in either case)")
    if args.raw_transcript and (args.no_goal or args.no_action):
        parser.error("--raw-transcript is mutually exclusive with --no-goal/--no-action "
                      "(no category filtering applies to the raw transcript)")
    if args.hard_only and args.no_video and args.no_text:
        parser.error("--hard-only is meaningless combined with the blind setting itself "
                      "(--no-video --no-text) — blind IS what defines hard/easy here")
    return args


def _video_duration_seconds(video_path: Path) -> float:
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", str(video_path)],
        check=True, capture_output=True, text=True,
    )
    return float(out.stdout.strip())


def format_duration(seconds: float) -> str:
    minutes = round(seconds / 60)
    return f"{minutes} minutes ({int(round(seconds))} seconds)"


def _extract_clip(video_path: Path, start: float, end: float, out_path: Path, fps: float,
                   scale_width: int | None = STAGE_VIDEO_SCALE_WIDTH, crf: int = STAGE1_CRF) -> None:
    """Encodes at `fps` and (optionally) downscaled to `scale_width` — the fps passed to Gemini's
    video_metadata only controls how it *samples* whatever bytes it receives, and it applies
    MEDIA_RESOLUTION_LOW regardless; neither shrinks the file, so we downsample both frame rate
    and resolution here (native 1080p at native rate would be multi-GB).

    NOTE: `ffmpeg -ss` re-zeroes the output's timeline (frame at original `start` becomes 0s).
    For the stage2/3 shared clip we therefore pass start=0 and exclude the intro via Gemini's
    VideoMetadata.start_offset instead, so the model keeps ORIGINAL video time (verified: with
    start_offset the model still timestamps events in original coordinates)."""
    vf = f"fps={fps}"
    if scale_width is not None:
        vf += f",scale={scale_width}:-2"
    subprocess.run(
        ["ffmpeg", "-y", "-ss", f"{start:.3f}", "-i", str(video_path), "-t", f"{end - start:.3f}",
         "-an", "-vf", vf, "-c:v", "libx264", "-preset", "veryfast", "-crf", str(crf), str(out_path)],
        check=True, capture_output=True,
    )


def categories_of(ann: dict) -> list[str]:
    cat = ann.get("category")
    return cat if isinstance(cat, list) else [cat]


def load_action_goal_transcript(label_annotations: dict, include_action: bool = True,
                                  include_goal: bool = True) -> list[dict]:
    wanted = ({"ACTION"} if include_action else set()) | ({"GOAL"} if include_goal else set())
    items = [
        {"start": a["start"], "end": a["end"], "transcript_text": a.get("transcript_text", "")}
        for a in label_annotations["annotations"]
        if wanted & set(categories_of(a))
    ]
    items.sort(key=lambda i: i["start"])
    return items


_TXT_TRANSCRIPT_LINE = re.compile(r"^\[(\d+):(\d{2}):(\d{2}(?:\.\d+)?)\]\s*(.*)$")


def load_raw_transcript(dataset_dir: Path, label_annotations: dict) -> list[dict]:
    """Loads the literal source transcript that label_annotations.json's categorized spans were
    built from — every line, regardless of category — from <dataset>/transcripts/<transcript_file>
    (named by label_annotations.json's "transcript_file" field). Handles both forms seen across
    datasets: JSON (a list of {id, start, end, text, speaker, ...}) and plain text ("[H:MM:SS.mmm]
    text" per line, start only, no end)."""
    path = dataset_dir / "transcripts" / label_annotations["transcript_file"]
    if path.suffix == ".json":
        entries = [{"start": r["start"], "end": r["end"], "transcript_text": r["text"]}
                   for r in json.loads(path.read_text())]
    else:
        entries = []
        for line in path.read_text().splitlines():
            m = _TXT_TRANSCRIPT_LINE.match(line)
            if not m:
                continue
            h, minutes, seconds, text = m.groups()
            start = int(h) * 3600 + int(minutes) * 60 + float(seconds)
            entries.append({"start": start, "transcript_text": text})
    entries.sort(key=lambda e: e["start"])
    return entries


def filtered_context(entries: list[dict], reference_end: float | None, drop_timestamps: bool = False) -> str:
    """reference_end=None means no cutoff (stage2/3's full history). drop_timestamps strips the
    start/end fields after filtering (used for the --no-timestamps full-context setting) — the
    cutoff still applies first, using the timestamps, before they're removed from the output."""
    relevant = entries if reference_end is None else [e for e in entries if e["start"] < reference_end]
    if drop_timestamps:
        relevant = [{k: v for k, v in e.items() if k not in ("start", "end")} for e in relevant]
    return json.dumps(relevant, indent=2)


def timestamps_only_context(entries: list[dict]) -> str:
    """Ground-truth spans with the action/state DESCRIPTIONS stripped — just the bare timespans.
    Used for the stage2/3 (timestamp-answer) judge context so the model can't answer by looking
    up the described action's timestamp in the sheet; it must use the video to determine what
    happens at each candidate time. (stage1 keeps full descriptions — its answers are prose, not
    timestamp lookups, so there's no leak.)"""
    return json.dumps([f"{int(round(e['start']))}s-{int(round(e['end']))}s" for e in entries], indent=2)


def build_choices(item: dict) -> tuple[str, dict[str, str], str]:
    """Shuffle correct + incorrect answers deterministically per item, letter them A/B/C/...
    Returns (choices_block_text, {letter: answer_text}, correct_letter)."""
    incorrect = [v for k, v in item.items() if re.fullmatch(r"incorrect_answer\d+", k)]
    options = [(True, item["correct_answer"])] + [(False, v) for v in incorrect]
    rng = random.Random(f"{item['annotation_id']}:{item['stage']}")
    rng.shuffle(options)
    letters = list(string.ascii_uppercase[: len(options)])
    letter_map = {}
    correct_letter = None
    lines = []
    for letter, (is_correct, text) in zip(letters, options):
        letter_map[letter] = text
        lines.append(f"{letter}) {text}")
        if is_correct:
            correct_letter = letter
    return "\n".join(lines), letter_map, correct_letter


def load_output(output_file: Path, dataset: str, model: str) -> dict:
    if output_file.exists():
        return json.loads(output_file.read_text())
    return {"dataset": dataset, "model": model, "generated_at": None, "results": []}


def save_output(output_file: Path, output: dict) -> None:
    output["generated_at"] = datetime.now(timezone.utc).isoformat()
    output_file.write_text(json.dumps(output, indent=2))


def hard_keys_from_blind(dataset_dir: Path) -> set[str]:
    """--hard-only support: "annotation_id:stage" keys wrong in AT LEAST ONE of the
    dataset's blind runs (the temp=0 baseline plus any temp!=0 repeat passes sitting
    alongside it — see scoring.blind_run_paths). A 3-run repeat check found only
    ~33% of items were wrong in every run while another ~15% flipped right/wrong
    depending on which single run was used, so pooling across every run found (rather
    than trusting just the baseline) is required to not undercount the hard set — see
    hard_items.py for the full variance analysis. An item that never parsed
    to a letter in any run is excluded — neither hard nor easy — same convention
    scoring.blind_wrongness uses."""
    from scoring import blind_run_paths, blind_wrongness

    if not blind_run_paths(dataset_dir):
        sys.exit(f"--hard-only needs a blind run first: no eval_results_no_video_no_text*.json "
                  f"found under {dataset_dir} (run with --no-video --no-text)")
    by_key, _ = blind_wrongness(dataset_dir)
    return {key for key, entry in by_key.items() if entry["wrong"]}


def main():
    args = parse_args()
    model = args.model
    dataset_dir = ANNOTATION_VIDEOS_DIR / args.dataset
    VIDEO_FLOOR_SECONDS = video_floor_seconds(args.dataset)
    vqa_file = dataset_dir / "vqa.json"
    queries_file = dataset_dir / "gemini_queries.json"
    ground_truth_file = dataset_dir / "annotations" / "ground_truth_actions.json"
    label_annotations_file = dataset_dir / "annotations" / "label_annotations.json"
    # Public release: per-item timing (reference_start/end, video_window) and the video's name and
    # duration, standing in for gemini_queries.json / interview_queries.json / the video file when
    # those aren't available. Enough for every setting that sends no transcript text (blind, and
    # --only-video once the video itself is in place).
    item_metadata_file = dataset_dir / "item_metadata.json"
    item_metadata = json.loads(item_metadata_file.read_text()) if item_metadata_file.exists() else None
    strip_text = args.only_video or args.no_text
    output_suffix = ("_no_video" if args.no_video else "") + ("_only_video" if args.only_video else "") \
        + ("_no_goal" if args.no_goal else "") + ("_no_action" if args.no_action else "") \
        + ("_no_text" if args.no_text else "") + ("_no_timestamps" if args.no_timestamps else "") \
        + ("_no_ground_truth" if args.no_ground_truth else "") + ("_raw_transcript" if args.raw_transcript else "")
    # A non-default model gets its own filename so its results never overwrite the default
    # model's baseline (e.g. eval_results_only_video_model_gemini_3_1_flash_lite.json).
    if model != MODEL:
        output_suffix += "_model_" + re.sub(r"[^a-z0-9]+", "_", model.lower()).strip("_")
    if args.temperature != INFERENCE_TEMPERATURE:
        output_suffix += "_temp" + re.sub(r"[^a-z0-9]+", "_", str(args.temperature)).strip("_")
    output_file = dataset_dir / f"eval_results{output_suffix}.json"
    if args.no_video and strip_text:
        prompt_template = PROMPT_TEMPLATE_BLIND
    elif args.no_video:
        prompt_template = PROMPT_TEMPLATE_NO_VIDEO
    elif strip_text:
        prompt_template = PROMPT_TEMPLATE_ONLY_VIDEO
    else:
        prompt_template = PROMPT_TEMPLATE

    if not vqa_file.exists():
        sys.exit(f"vqa.json not found: {vqa_file} (run vqa_pipeline/build_vqa.py first)")
    needs_ground_truth = not (strip_text or args.no_ground_truth)
    if not ground_truth_file.exists() and needs_ground_truth:
        sys.exit(f"ground_truth_actions.json not found: {ground_truth_file} "
                  "(required unless run with --no-text/--only-video/--no-ground-truth)")

    from dotenv import load_dotenv
    load_dotenv(DOTENV_FILE)
    _creds_path = Path(os.environ["GOOGLE_APPLICATION_CREDENTIALS"])
    if not _creds_path.is_absolute():
        _creds_path = (DOTENV_FILE.parent / _creds_path).resolve()
    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = str(_creds_path)
    vertex_project = json.loads(_creds_path.read_text())["project_id"]

    from google import genai
    from google.genai import types

    client = genai.Client(vertexai=True, project=vertex_project, location=VERTEX_LOCATION)

    def video_part(clip_bytes: bytes, fps: float, start_offset: str | None = None):
        vm = types.VideoMetadata(fps=fps, start_offset=start_offset) if start_offset \
            else types.VideoMetadata(fps=fps)
        return types.Part(
            inline_data=types.Blob(data=clip_bytes, mime_type="video/mp4"),
            video_metadata=vm,
        )

    last_call = [0.0]  # wall-clock of the last request start, for proactive throttling

    @retry(stop=stop_after_attempt(6), wait=wait_random_exponential(multiplier=2, min=4, max=60),
           retry=retry_if_exception(_is_retryable), reraise=True)
    def call_gemini(prompt: str, context_parts: list | None = None,
                     cached_content: str | None = None) -> tuple[str, dict]:
        """context_parts are the video/text context Parts sent inline (stage1 always; stage2/3
        under --no-cache). cached_content is the alternative for stage2/3: the identical context
        lives server-side in a cache and is referenced by handle instead of resent. Either way
        the prompt string itself carries only the question + choices, never the context."""
        wait = MIN_SECONDS_BETWEEN_CALLS - (time.monotonic() - last_call[0])
        if wait > 0:
            time.sleep(wait)
        last_call[0] = time.monotonic()
        contents = [prompt, *(context_parts or [])]
        config_kwargs = {"temperature": args.temperature}
        if any(p.inline_data is not None for p in (context_parts or [])):
            config_kwargs["media_resolution"] = types.MediaResolution.MEDIA_RESOLUTION_LOW
        if cached_content is not None:
            config_kwargs["cached_content"] = cached_content
        response = client.models.generate_content(
            model=model, contents=contents, config=types.GenerateContentConfig(**config_kwargs),
        )
        return response.text, _response_metadata(response)

    items = json.loads(vqa_file.read_text())
    if args.stage is not None:
        items = [i for i in items if i["stage"] == args.stage]
    if args.hard_only:
        hard_keys = hard_keys_from_blind(dataset_dir)
        before = len(items)
        items = [i for i in items if f"{i['annotation_id']}:{i['stage']}" in hard_keys]
        print(f"--hard-only: {before} -> {len(items)} items (blind-wrong; "
              f"{before - len(items)} dropped as blind-correct or blind-unevaluated)")

    if queries_file.exists():
        queries_by_id = {r["annotation_id"]: r for r in json.loads(queries_file.read_text())["results"]}
    elif item_metadata is not None:
        queries_by_id = item_metadata["queries"]
    else:
        sys.exit(f"Neither {queries_file} nor {item_metadata_file} found")
    ground_truth_actions = json.loads(ground_truth_file.read_text()) if ground_truth_file.exists() else []
    if label_annotations_file.exists():
        label_annotations = json.loads(label_annotations_file.read_text())
    elif strip_text:
        label_annotations = {"annotations": []}  # no transcript is sent in this setting anyway
    else:
        sys.exit(f"label_annotations.json not found: {label_annotations_file} "
                  "(required unless run with --no-text/--only-video)")

    # interview stage: read interview_queries.json for each item's [reference_start, reference_end]
    # (stated as text in the prompt, since the shared whole-video cache can't carry per-item
    # metadata) and the reference video's name. Its text context is the same full-history
    # ground_truth/transcript pipeline stage2/3 uses (see text_context_parts() below), so every
    # context flag (--no-action/--no-goal/--no-ground-truth/--no-timestamps/--raw-transcript) plus
    # --no-video/--only-video/--no-text applies to it too.
    interview_queries_file = dataset_dir / "interview_queries.json"
    interview_queries_by_id = {}
    interview_reference_video_name = None
    if interview_queries_file.exists():
        interview_queries_data = json.loads(interview_queries_file.read_text())
        interview_queries_by_id = {r["annotation_id"]: r for r in interview_queries_data["results"]}
        interview_reference_video_name = interview_queries_data.get("video")
    elif item_metadata is not None:
        interview_queries_by_id = item_metadata["interview_queries"]
        interview_reference_video_name = item_metadata["video"]

    if args.raw_transcript:
        transcript_entries = load_raw_transcript(dataset_dir, label_annotations)
        transcript_desc = "raw, all lines"
    else:
        transcript_entries = load_action_goal_transcript(
            label_annotations, include_action=not args.no_action, include_goal=not args.no_goal
        )
        transcript_label = "/".join(
            label for label, included in (("ACTION", not args.no_action), ("GOAL", not args.no_goal)) if included
        ) or "(none)"
        transcript_desc = f"{transcript_label} lines only"

    if queries_file.exists():
        video_name = json.loads(queries_file.read_text()).get("video") or label_annotations.get("video")
    else:
        video_name = item_metadata["video"]
    video_path = dataset_dir / "videos" / video_name
    if video_path.exists():
        duration = _video_duration_seconds(video_path)
    elif args.no_video and item_metadata is not None:
        duration = item_metadata["video_duration_seconds"]
    else:
        sys.exit(f"video not found: {video_path}")
    video_duration_text = format_duration(duration)

    output = load_output(output_file, args.dataset, model)
    done_keys = {r["key"] for r in output["results"]}
    todo = [i for i in items if f"{i['annotation_id']}:{i['stage']}" not in done_keys]
    if args.limit is not None:
        todo = todo[: args.limit]

    print(f"{len(items)} vqa items selected, {len(todo)} remaining to evaluate ({len(done_keys)} already done).")
    if not todo:
        print("Nothing to do.")
        return

    # ── Stage2/3 shared context: video clip + full history text, identical across all
    # stage2/3 items. Either cached (default) or held for inline resend (--no-cache). Only
    # built if we actually have stage2/3 work to do. Under caching, clip extraction is deferred
    # into build_contents() so a cache HIT (see vertex_cache.get_or_create) skips the ffmpeg
    # encode entirely instead of redoing it just to throw the bytes away. ──
    stage23_cache_name = None
    stage23_clip_bytes = None
    stage23_gt_text = ("Ground truth action timestamps (entire experiment), descriptions withheld:\n"
                       + timestamps_only_context(ground_truth_actions))
    stage23_transcript_text = f"Experiment transcript, {transcript_desc}:\n" + filtered_context(
        transcript_entries, None, drop_timestamps=args.no_timestamps)
    stage23_start_offset = f"{int(VIDEO_FLOOR_SECONDS)}s"
    include_gt = not (strip_text or args.no_ground_truth)

    # A dataset's goal/ folder (external reference material — e.g. a protocol sheet, a separate
    # interview transcript — for datasets with no GOAL-tagged label_annotations.json lines at
    # all) is purely additive: "" for every dataset that doesn't have one, so this changes
    # nothing for existing datasets. Not time-filtered, same reasoning as the GOAL-tagged text
    # already mixed into transcript_entries: goal material is stated up front and holds
    # throughout, so every item (stage1 included) gets the same block.
    goal_folder_text = load_goal_folder_text(dataset_dir)
    include_goal_folder = bool(goal_folder_text) and not (strip_text or args.no_goal)
    goal_folder_part = (types.Part(text=f"Experiment goal (reference material):\n{goal_folder_text}")
                         if include_goal_folder else None)

    def describe_text_context() -> str:
        if strip_text:
            return "NO textual context (--only-video/--no-text)"
        gt_desc = "full ground_truth_actions + " if include_gt else "NO ground_truth_actions (--no-ground-truth) + "
        goal_desc = " + goal/ folder reference material" if include_goal_folder else ""
        return (f"{gt_desc}full transcript ({transcript_desc})"
                f"{' (no timestamps)' if args.no_timestamps else ''}{goal_desc}")

    def text_context_parts() -> list:
        """Full-history text context: ground_truth_actions (timestamps only, subject to
        --no-ground-truth) + the ACTION/GOAL (or raw) transcript, subject to --no-action/--no-goal/
        --raw-transcript/--no-timestamps + a dataset's goal/ folder text, if it has one (subject to
        --no-goal). Shared by stage2/3 and interview — both use the complete history rather than a
        per-item cutoff (unlike stage1, which is scoped to its own clip)."""
        parts = []
        if include_gt:
            parts.append(types.Part(text=stage23_gt_text))
        if not strip_text:
            parts.append(types.Part(text=stage23_transcript_text))
        if goal_folder_part is not None:
            parts.append(goal_folder_part)
        return parts

    if any(i["stage"] in ("stage2", "stage3") for i in todo):
        clip_end = None
        text_desc = describe_text_context()
        if not args.no_video:
            # Encode from 0 (NOT from VIDEO_FLOOR) so the clip keeps original video time; the
            # intro before VIDEO_FLOOR is excluded at request time via start_offset, not by
            # cutting.
            clip_end = duration if args.max_clip_seconds is None \
                else min(duration, VIDEO_FLOOR_SECONDS + args.max_clip_seconds)
            print(f"Shared stage2/3 context: video [0s-{clip_end:.1f}s] at {STAGE23_FPS}fps "
                  f"@{STAGE_VIDEO_SCALE_WIDTH}px, start_offset={stage23_start_offset} "
                  f"{'(INLINE, --no-cache)' if args.no_cache else '(video cached)'} + {text_desc} (inline)...")
        else:
            print(f"Shared stage2/3 context: NO VIDEO (--no-video) + {text_desc} (inline)...")

        def build_stage23_clip_bytes():
            import tempfile
            def extract_at(crf):
                with tempfile.TemporaryDirectory() as tmp_dir:
                    clip_path = Path(tmp_dir) / "stage23_shared.mp4"
                    _extract_clip(video_path, 0.0, clip_end, clip_path, STAGE23_FPS, crf=crf)
                    return clip_path.read_bytes()
            max_bytes = STAGE23_CACHE_MAX_BYTES_BY_MODEL.get(model, STAGE23_CACHE_MAX_BYTES)
            data, _ = vertex_cache.encode_under_size_limit(extract_at, STAGE23_CRF, max_bytes=max_bytes)
            print(f"  cut shared clip ({len(data) / 1e6:.1f} MB)")
            return data

        # The cache holds VIDEO ONLY, never text — text context (ground_truth/transcript, and
        # which baseline flags shaped it) changes across eval settings far more often than the
        # video encoding does, and re-bundling text into the cache key meant every text-only
        # change forced a full cache rebuild (re-encoding + re-uploading the whole-video clip)
        # just to change what's the cheap, small part. So text is always sent inline per call
        # (never cached — a minor cost since it's tiny next to the video), while the video cache
        # is keyed only on its own encoding params + source file identity, and survives across
        # any number of different text-context settings.
        if not args.no_video:
            if args.no_cache:
                stage23_clip_bytes = build_stage23_clip_bytes()
            else:
                def build_video_only_contents():
                    return [video_part(build_stage23_clip_bytes(), STAGE23_FPS,
                                        start_offset=stage23_start_offset)]

                video_sig = (lambda st: f"{video_path.name}:{st.st_mtime_ns}:{st.st_size}:{clip_end:.1f}"
                             )(video_path.stat())
                cache_key = (f"eval_stage23_video|model={model}|fps={STAGE23_FPS}|scale={STAGE_VIDEO_SCALE_WIDTH}"
                             f"|crf={STAGE23_CRF}|floor={VIDEO_FLOOR_SECONDS}|video={video_sig}")
                stage23_cache_name, reused = vertex_cache.get_or_create(
                    client, types, dataset_dir, cache_key, model, STAGE23_CACHE_TTL_SECONDS,
                    build_video_only_contents,
                )
                print(f"  {'reusing live cache' if reused else 'cache created'} (video only): "
                      f"{stage23_cache_name} (ttl={STAGE23_CACHE_TTL_SECONDS}s); text sent inline every call")
        elif strip_text:
            # Fully blind (--no-video + strip_text): nothing to send — bare prompts.
            print("  nothing to send for shared context (no video, no text) — sending bare prompts")

    # ── Interview: one whole-reference-video CachedContent, identical across every interview item
    # — reuses the exact cache query_gemini_annotations.py --interview and
    # generate_adversarial_grounded.py already built (same key format, so a default-model run hits
    # it instead of re-encoding). Text context is the SAME full-history pipeline stage2/3 uses
    # (text_context_parts(): ground_truth_actions + ACTION/GOAL-or-raw transcript, subject to
    # --no-action/--no-goal/--no-ground-truth/--no-timestamps/--raw-transcript) sent inline, since a
    # cached video's own metadata can't be overridden per call. Video is included unless --no-video.
    # Each item's [reference_start, reference_end] is stated as text in the prompt so the model
    # knows where in the whole video to look. ──
    interview_cache_name = None
    interview_clip_bytes = None
    if any(i["stage"] == "interview" for i in todo):
        if not interview_reference_video_name:
            sys.exit("interview_queries.json not found or has no 'video' field — needed for the "
                      "reference video (run query_gemini_annotations.py --interview first)")
        interview_video_path = dataset_dir / "videos" / interview_reference_video_name
        if not args.no_video:
            if not interview_video_path.exists():
                sys.exit(f"interview reference video not found: {interview_video_path}")
            interview_duration = _video_duration_seconds(interview_video_path)
        text_desc = describe_text_context()

        if not args.no_video:
            print(f"Shared interview context: whole video [0s-{interview_duration:.1f}s] at "
                  f"{INTERVIEW_FPS}fps @{INTERVIEW_VIDEO_SCALE_WIDTH}px "
                  f"{'(INLINE, --no-cache)' if args.no_cache else '(cache)'} + {text_desc} (inline)...")

            def build_interview_clip_bytes():
                import tempfile
                def extract_at(crf):
                    with tempfile.TemporaryDirectory() as tmp_dir:
                        clip_path = Path(tmp_dir) / "interview_reference_whole.mp4"
                        _extract_clip(interview_video_path, 0.0, interview_duration, clip_path,
                                      INTERVIEW_FPS, scale_width=INTERVIEW_VIDEO_SCALE_WIDTH,
                                      crf=crf)
                        return clip_path.read_bytes()
                max_bytes = STAGE23_CACHE_MAX_BYTES_BY_MODEL.get(model, STAGE23_CACHE_MAX_BYTES)
                data, _ = vertex_cache.encode_under_size_limit(extract_at, INTERVIEW_CRF, max_bytes=max_bytes)
                print(f"  cut whole-reference-video clip ({len(data) / 1e6:.1f} MB)")
                return data

            if args.no_cache:
                interview_clip_bytes = build_interview_clip_bytes()
            else:
                def build_interview_cache_contents():
                    return [video_part(build_interview_clip_bytes(), INTERVIEW_FPS)]

                ist = interview_video_path.stat()
                interview_cache_key = (
                    f"interview_whole|model={model}|fps={INTERVIEW_FPS}|scale={INTERVIEW_VIDEO_SCALE_WIDTH}"
                    f"|crf={INTERVIEW_CRF}|video={interview_video_path.name}:{ist.st_mtime_ns}:{ist.st_size}"
                    f":{interview_duration:.1f}"
                )
                interview_cache_name, reused = vertex_cache.get_or_create(
                    client, types, dataset_dir, interview_cache_key, model, INTERVIEW_CACHE_TTL_SECONDS,
                    build_interview_cache_contents,
                )
                print(f"  {'reusing live cache' if reused else 'cache created'}: {interview_cache_name} "
                      f"(ttl={INTERVIEW_CACHE_TTL_SECONDS}s)")
        else:
            print(f"Shared interview context: NO VIDEO (--no-video) + {text_desc} (inline)...")

    for i, item in enumerate(todo, 1):
        key = f"{item['annotation_id']}:{item['stage']}"
        if item["stage"] == "interview":
            ref = interview_queries_by_id.get(item["annotation_id"])
            if ref is None:
                print(f"[{i}/{len(todo)}] {key}: no matching interview_queries.json entry, skipping")
                continue
        else:
            ref = queries_by_id.get(item["annotation_id"])
            if ref is None:
                print(f"[{i}/{len(todo)}] {key}: no matching gemini_queries.json entry, skipping")
                continue

        choices_block, letter_map, correct_letter = build_choices(item)
        print(f"[{i}/{len(todo)}] {key} ({item['category']!r}), correct={correct_letter}")

        prompt = prompt_template.format(question=item["question"], choices_block=choices_block,
                                         video_duration=video_duration_text)

        if item["stage"] == "stage1":
            # Per-item context, inline: this item's own ~30s clip + text history up to its
            # reference_end (matching how the stage1 question was generated). Under --no-video
            # the clip is skipped entirely — only the text context is sent.
            reference_end = ref["reference_end"]

            context_parts = []
            if include_gt:
                context_parts.append(types.Part(text="Ground truth actions (up to this point):\n"
                                                      + filtered_context(ground_truth_actions, reference_end)))
            if not strip_text:
                context_parts.append(types.Part(
                    text=f"Experiment transcript, {transcript_desc} (up to this point):\n"
                         + filtered_context(transcript_entries, reference_end,
                                            drop_timestamps=args.no_timestamps)))
            if goal_folder_part is not None:
                context_parts.append(goal_folder_part)
            if not args.no_video:
                vw = ref["video_window"]
                window_start = max(VIDEO_FLOOR_SECONDS, vw["start"])
                window_end = max(window_start + 1.0, vw["end"])
                import tempfile
                with tempfile.TemporaryDirectory() as tmp_dir:
                    clip_path = Path(tmp_dir) / f"{item['annotation_id']}.mp4"
                    _extract_clip(video_path, window_start, window_end, clip_path, STAGE1_FPS)
                    clip_bytes = clip_path.read_bytes()
                context_parts.insert(0, video_part(clip_bytes, STAGE1_FPS))
            response, usage = call_gemini(prompt, context_parts=context_parts)
        elif item["stage"] == "interview":
            # Same full-history text context as stage2/3 (ground_truth + ACTION/GOAL-or-raw
            # transcript, subject to the same flags), inline; video via the shared
            # whole-reference-video cache (or inline under --no-cache), with the item's
            # [reference_start, reference_end] stated as text since the cached video can't carry
            # per-item metadata.
            context_parts = text_context_parts()
            cached_content = None
            if not args.no_video:
                if args.no_cache:
                    context_parts.insert(0, video_part(interview_clip_bytes, INTERVIEW_FPS))
                else:
                    cached_content = interview_cache_name
                context_parts.append(types.Part(
                    text=f"This question is about the moment in the video from "
                         f"{ref['reference_start']:.1f}s to {ref['reference_end']:.1f}s."))
            response, usage = call_gemini(prompt, context_parts=context_parts, cached_content=cached_content)
        else:
            # Stage2/3: text context (ground_truth/transcript) is always sent inline — it's what
            # varies across eval settings. Video is either inline too (--no-cache) or supplied via
            # the video-only cache; with --no-video there's no video contribution either way.
            context_parts = text_context_parts()
            # Stage2 (PLAN) questions describe "the current point" in whatever way Gemini's own
            # question-writing chose to — a present-tense action ("is increasing the stirring
            # speed"), or sometimes nothing at all, just a bare "this step"/"this precise
            # measurement" pronoun with no restated description — and the stage2/3 history above
            # is sent in full, uncut, so nothing else in the context pins down which moment that
            # is. The disclosure below must therefore explicitly bind "current point"/"now"/
            # "this"/"this step" (however the question phrases it) to the given timestamp, not
            # just assert a "current point" the question may never actually name. Sent regardless
            # of --no-video (it's part of the question's text context, not the video context)
            # since the transcript is untruncated either way. current_point is build_vqa.py's
            # carry-through of Gemini's own future_event identification from stage2 generation.
            if item["stage"] == "stage2" and item.get("current_point"):
                context_parts.append(types.Part(
                    text=f"The question below refers to the present moment of the experiment — "
                         f"'currently', 'now', 'this', 'this step', or however else it phrases "
                         f"it — as the video interval {item['current_point']}. Use what happens "
                         f"in that interval to identify what the question is asking about, then "
                         f"answer about what came before it."))
            cached_content = None
            if not args.no_video:
                if args.no_cache:
                    context_parts.insert(0, video_part(stage23_clip_bytes, STAGE23_FPS,
                                                        start_offset=stage23_start_offset))
                else:
                    cached_content = stage23_cache_name
            response, usage = call_gemini(prompt, context_parts=context_parts, cached_content=cached_content)

        output["results"].append({
            "key": key,
            "annotation_id": item["annotation_id"],
            "stage": item["stage"],
            "category": item["category"],
            "question": item["question"],
            "choices": letter_map,
            "correct_letter": correct_letter,
            "prompt": prompt,
            "response": response,
            "usage": usage,
        })
        save_output(output_file, output)  # incremental write — safe to interrupt/resume

    print(f"Wrote {len(output['results'])} total results to {output_file}")


if __name__ == "__main__":
    main()
